Repository awaisanwar544/final-capstone-api, pull requests merged in 2022-07, with the labels that each got.

#19 Final Capstone API: Setup Rails and Linters
  .gitattributes
  .github/workflows/linters.yml
  .gitignore
  .rspec
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/bundle.cmd
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  spec/rails_helper.rb
  spec/spec_helper.rb
  storage/.keep
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/test_helper.rb
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: enhancement

#24 Final Capstone: Provider endpoints
  Gemfile
  Gemfile.lock
  app/controllers/api/providers_controller.rb
  app/models/provider.rb
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  config/storage.yml
  db/migrate/20220707162902_create_providers.rb
  db/migrate/20220708160218_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: enhancement

#29 Final Capstone: Skills and Providers
  app/controllers/api/providers_controller.rb
  app/controllers/api/skills_controller.rb
  app/models/provider.rb
  app/models/skill.rb
  config/routes.rb
  db/migrate/20220707163512_create_skills.rb
  db/migrate/20220711184733_create_join_table_provider_skill.rb
  db/schema.rb
Labels: enhancement

#30 Final Capstone: Forgot Password
  Gemfile
  Gemfile.lock
  app/controllers/passwords_controller.rb
  app/controllers/users_controller.rb
  app/mailers/notifier_mailer.rb
  app/models/user.rb
  app/views/notifier_mailer/send_password_reset_email.html.erb
  config/credentials.yml.enc
  config/environment.rb
  config/environments/development.rb
  config/initializers/cors.rb
  config/routes.rb
  db/migrate/20220712100026_add_password_reset_columns_to_user.rb
  db/schema.rb
  spec/mailers/notifier_spec.rb
  spec/mailers/previews/notifier_preview.rb
  spec/requests/passwords_spec.rb
Labels: enhancement

#32 Fix bugs
  app/controllers/api/providers_controller.rb
  app/controllers/api/reservations_controller.rb
  app/controllers/api/skills_controller.rb
  app/controllers/application_controller.rb
  app/controllers/passwords_controller.rb
  app/models/provider.rb
  config/routes.rb
  spec/requests/provider_spec.rb
Labels: bug

#33 Add tests for reservations controller
  app/controllers/api/reservations_controller.rb
  spec/requests/reservations_spec.rb
Labels: enhancement

#35 Final Capstone: API Documentation
  Gemfile
  Gemfile.lock
  app/controllers/api/reservations_controller.rb
  app/controllers/application_controller.rb
  app/models/reservation.rb
  app/views/rswag/ui/home/index.html.erb
  config/environments/production.rb
  config/initializers/rswag-ui.rb
  config/initializers/rswag_api.rb
  config/routes.rb
  db/schema.rb
  public/api-docs/absolute-path.js
  public/api-docs/bookDev.jpg
  public/api-docs/favicon-16x16.png
  public/api-docs/favicon-32x32.png
  public/api-docs/favicon.ico
  public/api-docs/index.js
  public/api-docs/swagger-ui-bundle.js
  public/api-docs/swagger-ui-es-bundle-core.js
  public/api-docs/swagger-ui-es-bundle.js
  public/api-docs/swagger-ui-standalone-preset.js
  public/api-docs/swagger-ui.css
  public/api-docs/swagger-ui.js
  public/favicon.ico
  spec/controllers/passwords_spec.rb
  spec/controllers/provider_spec.rb
  spec/controllers/reservations_spec.rb
  spec/controllers/users_spec.rb
  spec/requests/passwords_documents_spec.rb
  spec/requests/providers_documents_spec.rb
  spec/requests/reservations_documents_spec.rb
  spec/requests/users_documents_spec.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.json
  swagger/v1/swagger.yaml
Labels: documentation, enhancement

#36 Final Capstone: Deployment
  README.md
  config/environments/production.rb
Labels: enhancement
